export default {
  cohort: 17,
  conversation_welcome_message: 'JavaScript ES2018, jQuery, or React course for VanArts',
  assessment: {
    classNumber: '01',
    course: 'jquery',
    students: {
      SlackBot: {
        latestNote: 'Second assignment',
        homework: [[3, 6], [3, 6]],
        slackUserId: 'D0425RJBT',
        slackMemberId: 'USLACKBOT',
        githubUsername: null,
      },
      Maria_Lavetkina: {
        latestNote: 'Slack and GitHub setup',
        homework: [[5, 5]],
        final: [],
        slackUserId: 'DV3DPCRL4',
        slackMemberId: 'UV3T51KLM',
        githubUsername: 'maria-lav',
      },
      Negar_Bayat: {
        latestNote: 'Slack and GitHub setup',
        homework: [[5, 5]],
        final: [],
        slackUserId: 'DV44SQXDE',
        slackMemberId: 'UV6AZ0D3Q',
        githubUsername: 'Negar609',
      },
      Pinlun_Chen: {
        latestNote: 'Slack and GitHub setup',
        homework: [[5, 5]],
        final: [],
        slackUserId: 'DUR630X18',
        slackMemberId: 'UV64J24JJ',
        githubUsername: 'pinlunCH',
      },
      Price_Hu: {
        latestNote: 'Slack and GitHub setup',
        homework: [[5, 5]],
        final: [],
        slackUserId: 'DUPJTEZ7U',
        slackMemberId: 'UUS9WCK41',
        githubUsername: 'hgppppprice',
      },
      Tife_Obideyi: {
        latestNote: 'Slack and GitHub setup',
        homework: [[5, 5]],
        final: [],
        slackUserId: 'DUSL30REF',
        slackMemberId: 'UV4103ZDE',
        githubUsername: 'TifeLaflame',
      },
      Mana: {
        latestNote: 'Slack and GitHub setup',
        homework: [[5, 5]],
        final: [],
        slackUserId: 'DV65ZNYR2',
        slackMemberId: 'UUTRKQMDY',
        githubUsername: 'ManashreePatil',
      },
      Ashwim: {
        latestNote: 'GitHub username is missing',
        homework: [[3, 5]],
        final: [],
        slackUserId: 'DUWJQJ3K5',
        slackMemberId: 'UV7H2V2NQ',
        githubUsername: null,
      },
    },
  },
};
